In [ ]:
#Aufgabe 2


In [36]:
%%timeit i=432231; a=[];
while i >430989:
    a= a + [i]
    i= i-2


51.1 ns ± 1.82 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [38]:
%%timeit i=432231; a=[];
while i >430989:
    a+=[i]
    i-=2


51.9 ns ± 0.927 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [39]:
print(a)

[432231, 432229, 432227, 432225, 432223, 432221, 432219, 432217, 432215, 432213, 432211, 432209, 432207, 432205, 432203, 432201, 432199, 432197, 432195, 432193, 432191, 432189, 432187, 432185, 432183, 432181, 432179, 432177, 432175, 432173, 432171, 432169, 432167, 432165, 432163, 432161, 432159, 432157, 432155, 432153, 432151, 432149, 432147, 432145, 432143, 432141, 432139, 432137, 432135, 432133, 432131, 432129, 432127, 432125, 432123, 432121, 432119, 432117, 432115, 432113, 432111, 432109, 432107, 432105, 432103, 432101, 432099, 432097, 432095, 432093, 432091, 432089, 432087, 432085, 432083, 432081, 432079, 432077, 432075, 432073, 432071, 432069, 432067, 432065, 432063, 432061, 432059, 432057, 432055, 432053, 432051, 432049, 432047, 432045, 432043, 432041, 432039, 432037, 432035, 432033, 432031, 432029, 432027, 432025, 432023, 432021, 432019, 432017, 432015, 432013, 432011, 432009, 432007, 432005, 432003, 432001, 431999, 431997, 431995, 431993, 431991, 431989, 431987, 431985, 431983,

In [49]:
Summe_a=0
u=0
for u in range (len(a)):
    Summe_a+=a[u]
    u+=1
print(Summe_a)

268030431


In [267]:

#Aufgabe 3

deutsch_english = {"Haus":"house","Hund":"dog","Maus":"mouse","Katze":"cat"}
keys={1:'Haus', 2:'Hund', 3:'Maus', 4:'Katze'}
i=1
c=""
d=""
z=True
while i in range(1,len(deutsch_english)+1):
    if z!=True:
        print("Programm beendet")
        break
    print("Zu übersetzendes Wort:", keys[i])
    c = input("Übersetzung eingeben:")
    d=deutsch_english[keys[i]]
    if c == d:
        print("Richtig, hier ein neues")
        i+=1
    elif c!=d:
        print("Leider Falsch")
        u = int(input("'1' für nochmal, '0' zum beenden:"))
        if u==1:
            z=True
        else:
            z=False

Zu übersetzendes Wort: Haus


Übersetzung eingeben: hs


Leider Falsch


'1' für nochmal, '0' zum beenden: 1


Zu übersetzendes Wort: Haus


Übersetzung eingeben: house


Richtig, hier ein neues
Zu übersetzendes Wort: Hund


Übersetzung eingeben: dh


Leider Falsch


'1' für nochmal, '0' zum beenden: 1


Zu übersetzendes Wort: Hund


Übersetzung eingeben: dog


Richtig, hier ein neues
Zu übersetzendes Wort: Maus


Übersetzung eingeben: hdj


Leider Falsch


'1' für nochmal, '0' zum beenden: 0


Programm beendet


In [ ]:

#Aufgabe 4


In [2]:
s= 'Python ist cool'
sonder= ' !"#$%&)))(*§+,-./:;<=>?@[\\]^_`{|}~'
buchst=[]
Anzahl=[]
i4=0
for i4 in range (len(s)):
    i4_1=0
    
    if len(buchst)==0:
        buchst+=s[i4]
        i4+=1
        Anzahl.append(0)
    for i4_1 in range (len(buchst)+1):
        if s[i4]==buchst[i4_1-1]:
            i4+=1
            break
        elif i4_1 == len(buchst):
            buchst+=s[i4]
            Anzahl.append(0)
            i4+=1
            break
        else: 
            i4_1+=1
            
i4_3=0
for i4_3 in range (len(s)):
    i4_4=0
    for i4_4 in range (len(buchst)):
        if i4_4==len(buchst):
            i4_3+=1
            break
        elif buchst[i4_4]==s[i4_3]:
            Anzahl[i4_4]+=1
            break
        else:
            i4_4+=1
    i4_3+=1

i4_8=0
for i4_8 in range (len (buchst)-1):
    for i4_9 in range (len (sonder)):
        if i4_8> len(buchst)-1:
            break
        elif buchst[i4_8]==sonder[i4_9]:
            buchst.pop(i4_8)
            Anzahl.pop(i4_8) 
            i4_8+=1
            break
        else:      
            i4_9+=1

lauf4=0
for i4_7 in range (len(buchst)):
    lauf4=0
    for i4_6 in range (len (buchst)):
        if lauf4 > Anzahl[i4_6]:
            i4_6+=1
        else:
            lauf4=Anzahl[i4_6]

    for i4_6 in range (len (buchst)):
        
        if lauf4 == Anzahl[i4_6]: 
            print (buchst[i4_6], 'kommt', Anzahl[i4_6], 'mal vor')
            Anzahl.remove(Anzahl[i4_6])
            buchst.remove(buchst[i4_6])
            break
        else:
            i4_6+=1

o kommt 3 mal vor
t kommt 2 mal vor
P kommt 1 mal vor
y kommt 1 mal vor
h kommt 1 mal vor
n kommt 1 mal vor
i kommt 1 mal vor
s kommt 1 mal vor
c kommt 1 mal vor
l kommt 1 mal vor


In [ ]:
#b)

In [17]:
s= 'hier text eingeben!'
s_neu=[]
sonder= ' !"#$%&)))(*§+,-./:;<=>?@[\\]^_`{|}~'
buchst=[]
Anzahl=[]



i4_b=0
for i4_b in range(len(s)):
    i4_b1=0
    for i4_b1 in range (25):
        if ord(s[i4_b])==ord('a')+i4_b1:
            s_neu.append(chr(ord('A')+i4_b1))
        elif ord(s[i4_b])==ord('A')+i4_b1: 
            s_neu.append(s[i4_b])
        elif s[i4_b]=='ß':
            s_neu.append('S')
            s_neu.append('S')
            break
        else:
            i4_b1+=1
    i4_b+=1


i4=0
for i4 in range (len(s_neu)):
    i4_1=0
    
    if len(buchst)==0:
        buchst+=s_neu[i4]
        i4+=1
        Anzahl.append(0)
    for i4_1 in range (len(buchst)+1):
        if s_neu[i4]==buchst[i4_1-1]:
            i4+=1
            break
        elif i4_1 == len(buchst):
            buchst+=s_neu[i4]
            Anzahl.append(0)
            i4+=1
            break
        else: 
            i4_1+=1
            
i4_3=0
for i4_3 in range (len(s_neu)):
    i4_4=0
    for i4_4 in range (len(buchst)):
        if i4_4==len(buchst):
            i4_3+=1
            break
        elif buchst[i4_4]==s_neu[i4_3]:
            Anzahl[i4_4]+=1
            break
        else:
            i4_4+=1
    i4_3+=1

i4_8=0
for i4_8 in range (len (buchst)-1):
    for i4_9 in range (len (sonder)):
        if i4_8> len(buchst)-1:
            break
        elif buchst[i4_8]==sonder[i4_9]:
            buchst.pop(i4_8)
            Anzahl.pop(i4_8) 
            i4_8+=1
            break
        else:      
            i4_9+=1

lauf4=0
for i4_7 in range (len(buchst)):
    lauf4=0
    for i4_6 in range (len (buchst)):
        if lauf4 > Anzahl[i4_6]:
            i4_6+=1
        else:
            lauf4=Anzahl[i4_6]

    for i4_6 in range (len (buchst)):
        
        if lauf4 == Anzahl[i4_6]: 
            print (buchst[i4_6], 'kommt', Anzahl[i4_6], 'mal vor')
            Anzahl.remove(Anzahl[i4_6])
            buchst.remove(buchst[i4_6])
            break
        else:
            i4_6+=1

E kommt 5 mal vor
I kommt 2 mal vor
T kommt 2 mal vor
N kommt 2 mal vor
H kommt 1 mal vor
R kommt 1 mal vor
X kommt 1 mal vor
G kommt 1 mal vor
B kommt 1 mal vor


In [2]:
#Aufgabe 5:
#Um Numpy-Arrays umzuformen, bzw in verschiedene Dimensionen zu unterteilen muss man den Namen des Numpy-Arrays mit der Funktion reshape() 
#aufrufen, in diesen kann man dann, mithilfe von Kommas die Unterteilung aufrufen. 
#Beim Slicing kann man ein Numpy-Array in mehrere Abschnitte unterteilen, dies geschieht in dem man den Namen des Numpy-Arrays aufruft
#und in eckigen Klammern die unterteilung vornimmt, jedoch werden hier Doppelpunkte benutzt. Hierbei werden aber nur die ausgewählten Zahlen ausgegeben.
#Besispiele:

import numpy as np
a=range(10)
b=np.array(a)

print(b.reshape(2,5)) # Ausgabe der Werte 2-5

b
print(b[2:5]) 

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 3 4]


In [6]:
np.random.seed(42)
a=np.random.randint(0,10,100)
b=a[a<6].reshape(17,3)
# b hat dann die Form von 17 einzelnen Sparten mit jeweils 3 Werten

In [139]:
#Aufg.7

#a)
text='DIES IST EIN KLARTEXT'
passwort='SONNE'
verschlüsselt='' 

i7=0
i7_1=0

for i7 in range(len(text)):
    s=ord(text[i7])
    
    if chr(s)== ' ':
        verschlüsselt+=' '
        i7+=1
    elif chr(s)== '.':
        verschlüsselt+='.'
        i7+=1 
    elif chr(s)== ',':
        verschlüsselt+=','
        i7+=1
        
    else:
        s+=ord(passwort[i7_1%len(passwort)])+1
        if s>90:
            s = s%26 + 65
            verschlüsselt+=chr(s)
        i7_1+=1
    
print ('Verschlüsselter Text:', verschlüsselt) 

Verschlüsselter Text: WXSG NLI SWS DAOFYXMH


In [103]:
65-90-122

-147

In [142]:
#b)
text=''
passwort='PASSWORT'
verschlüsselt='fzmalc eusim lmpkm' 
verschlüsselt=verschlüsselt.upper()

i7=0
i7_1=0

for i7 in range(len(verschlüsselt)):
    s=ord(verschlüsselt[i7])
    if chr(s)== ' ':
        text+=' '
        i7+=1
    elif chr(s)== '.':
        text+='.'
        i7+=1 
    elif chr(s)== ',':
        text+=','
        i7+=1
       
    else:
        s-=ord(passwort[i7_1%len(passwort)])+1
        if s<65:
            s = s%26 + 65
            text+=chr(s)
        i7_1+=1
print ('entschlüsselter Text:', text) 

entschlüsselter Text: PYTHON MACHT SPASS


In [164]:
text='PYTHON MACHT SPASS'
passwort=''
pw_ganz=''
verschlüsselt='fzmalc eusim lmpkm'
verschlüsselt=verschlüsselt.upper()

i7=0

for i7 in range (len(text)):
    g=ord(text[i7])
    if chr(g)== ' ':
        i7+=1
    elif chr(g)== '.':
        i7+=1 
    elif chr(g)== ',':
        i7+=1
    else:
        g=ord(verschlüsselt[i7])-ord(text[i7])
    
        if g<65:
            g=g%26 + 65

        pw_ganz+=chr(g-1)
    
print (pw_ganz)







PASSWORTPASSWORT


In [ ]:
text=''
wahrsch_text='MACHT'
passwort=''
pw_ganz=''
verschlüsselt='fzmalc eusim lmpkm'
verschlüsselt=verschlüsselt.upper()

i7=0

for i7 in range (len(verschlüsselt)):
    g=ord(text[i7])
    if chr(g)== ' ':
        i7+=1
    elif chr(g)== '.':
        i7+=1 
    elif chr(g)== ',':
        i7+=1
    else:
        g=ord(verschlüsselt[i7])-ord(text[i7])
    
        if g<65:
            g=g%26 + 65

        pw_ganz+=chr(g-1)
    
print (pw_ganz)


In [174]:
#aufgabe 7 c)
#Keine Ahnung, wie ich dies realisieren soll, ohne angabe von der Länge des Passwortes.
#Ich hatte die Idee, einen Algorithmus zu schreiben, der nach dem Schlüsselwort sucht, indem er jedes Wort nach und nach mit Vigenere entschlüsselt,
#und guckt, ob das Wort rauskommt. Dies ist für mich auch in der vorgegebenen Zeit leider nicht realisierbar.

Keyword Length 1: fzmalc eusim lmpkm
Keyword Length 2: fymzlb etshm kmokl
Keyword Length 3: fykaka etqil jmoim
Keyword Length 4: fykxlb crshk imoij
Keyword Length 5: fykxhc dspem kkmgm
Keyword Length 6: fykxhx etqfi gmoij
Keyword Length 7: fykxhx yurgj hhjkl
Keyword Length 8: fykxhx ynshk iikef
Keyword Length 9: fykxhx ynkil jjlfg
Keyword Length 10: fykxhx ynkzm kkmgh
