# 5. Numerical Python mit NumPy 

In [428]:
import numpy as np

## 5.1 NumPy Arrays Grundlagen

In [429]:
a = [1,2,3,4,5,6,7,8,9]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [430]:
b = np.array(a)

b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [431]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\lmarien\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\lmarien\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snip

In [432]:
b[3] = 2.71

In [433]:
b

array([1, 2, 3, 2, 5, 6, 7, 8, 9])

In [434]:
b?

Type:        ndarray
String form: [1 2 3 2 5 6 7 8 9]
Length:      9
File:        c:\users\lmarien\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype

In [435]:
c = np.array([2,3,4,3.1415,1])

In [436]:
c

array([2.    , 3.    , 4.    , 3.1415, 1.    ])

In [437]:
c.sort()
c

array([1.    , 2.    , 3.    , 3.1415, 4.    ])

In [438]:
d = np.array(range(100))
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [439]:
t = (100,)

In [440]:
type(t)

tuple

In [441]:
d.shape

(100,)

In [442]:
d.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [443]:
d.reshape(2,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [444]:
d.reshape(1,100)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [445]:
np.zeros(10, dtype=str)

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [446]:
np.ones(10, dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [447]:
np.full((4,7),4711)

array([[4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711],
       [4711, 4711, 4711, 4711, 4711, 4711, 4711]])

In [448]:
e = np.array([range(index, index+13,3) for index in [9,8,5,4]])

In [449]:
e

array([[ 9, 12, 15, 18, 21],
       [ 8, 11, 14, 17, 20],
       [ 5,  8, 11, 14, 17],
       [ 4,  7, 10, 13, 16]])

In [450]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [451]:
np.arange(5,17,2,dtype=int)

array([ 5,  7,  9, 11, 13, 15])

In [452]:
np.linspace(5,25,10)

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [453]:
np.random.random(19)

array([0.03318676, 0.79182359, 0.37994064, 0.91834099, 0.43085472,
       0.46499877, 0.61076926, 0.39913314, 0.36316329, 0.69424354,
       0.53914654, 0.67250019, 0.53804305, 0.07917331, 0.54285343,
       0.52431492, 0.06534026, 0.882848  , 0.0379062 ])

In [454]:
np.random.random((5,5))

array([[0.17471767, 0.56755635, 0.60400998, 0.73444888, 0.1015775 ],
       [0.6392828 , 0.91148054, 0.63398321, 0.38478924, 0.24389047],
       [0.50550127, 0.18048832, 0.72259828, 0.33269475, 0.62101483],
       [0.20227649, 0.38103757, 0.51525074, 0.33359304, 0.52080639],
       [0.02839457, 0.33326332, 0.5979877 , 0.87269381, 0.81206461]])

In [455]:
mittelwert = -5
standardabweichung = 5
anzahl = 100
np.random.normal(mittelwert, standardabweichung, anzahl)

array([ -9.75844606,  -3.69502579,   4.12004292,  -7.15359677,
        -6.5001761 ,  -8.87944077,  -3.48063267,   2.86495505,
        -6.98054363,   0.73282459,  -7.27450726,  -5.23955858,
        -8.68051749,  -6.12476404, -10.02364336,  -7.28004939,
        -7.05229127,  -2.21929294,  -8.55566056,  -2.05366755,
        -7.68391009,  -2.85220093,  -2.41580822,  -8.44468885,
         4.17625321,  -6.11251181,  -5.22371902,  -5.62042483,
        -8.86726209,  -8.20256091,  -3.93216648,   5.42696846,
         1.05995589,   1.99098137,   2.37561189,  -2.08708726,
       -12.07683667,  -6.55424194,   3.20026105,   2.60446543,
        -3.79867753,  -2.69679766,  -5.10977744,  -8.54168961,
        -7.77147426,  -0.53188796,  -6.08030586,  -0.91630332,
        -5.05015017,   5.13628452, -12.59281102,  -8.65438317,
         0.02010903,  -3.26019496, -10.30811986,  -3.75758892,
        -7.59201366,   1.31016629,  -9.85672248, -12.88466222,
        -7.0030452 ,  -4.8907642 ,   0.64631145,  -5.56

In [456]:
np.random.normal(mittelwert, standardabweichung, (3,5,4))

array([[[ -5.63521099, -14.7290227 , -10.14246951, -13.49895823],
        [  5.46472159, -14.4563287 ,  -3.75394635,  -8.80758204],
        [ -4.82927361,  -6.99441254,  -0.78484924,  -1.18963525],
        [-13.80588246,  -7.37654331,  -6.40351541,  -3.03668907],
        [  1.40084264,  -6.10923855,  -1.94926233,  -6.97039617]],

       [[ -7.69473622, -12.3882361 ,  -7.59356159,  -6.13551764],
        [ -7.26053607,  -2.5768635 , -10.46180631,  -5.30859066],
        [ -1.27996206,  -7.88336188,  -5.57695551,   6.72889894],
        [-12.30395336,  -6.84786345, -12.64526193, -11.7102427 ],
        [ -7.59569905,  -9.67207797, -10.68025073,  -1.16039325]],

       [[ -4.06902799,  -8.27350569,   1.89840832,  -5.66051363],
        [-12.33225374,  -0.27322959,  -2.45822297,  -2.15705929],
        [  4.57969257,  -6.93215884, -13.33432167,  -0.19419976],
        [ -5.89608739,   0.67674488, -13.07265758,  -9.98649076],
        [-15.65137284,   3.85860564, -16.11328254,  -4.77921677]]])

In [457]:
np.random.seed(42)
von = 10  # inklusive
bis = 100 # exklusive
a1 = np.random.randint(von, bis, 10)
a2 = np.random.randint(von, bis, (2,3))
a3 = np.random.randint(von, bis, (3,4,5))
a4 = np.random.randint(von, bis, (3,2,5,2))
a5 = np.random.randint(von, bis, (4,5,6,2,2))
myArrays = [a1,a2,a3,a4,a5]

In [458]:
for i in range(len(myArrays)):
    print("a{0:}: Dimension {1:}, Size {2:3d}, Itemsize {3:}, NBytes {4:4d}, Shape {5:}".format(
        i+1,myArrays[i].ndim,
        myArrays[i].size,
        myArrays[i].itemsize,
        myArrays[i].nbytes,
        myArrays[i].shape))

a1: Dimension 1, Size  10, Itemsize 4, NBytes   40, Shape (10,)
a2: Dimension 2, Size   6, Itemsize 4, NBytes   24, Shape (2, 3)
a3: Dimension 3, Size  60, Itemsize 4, NBytes  240, Shape (3, 4, 5)
a4: Dimension 4, Size  60, Itemsize 4, NBytes  240, Shape (3, 2, 5, 2)
a5: Dimension 5, Size 480, Itemsize 4, NBytes 1920, Shape (4, 5, 6, 2, 2)


In [459]:
a1

array([61, 24, 81, 70, 30, 92, 96, 84, 84, 97], dtype=int32)

In [460]:
a1[5]

np.int32(92)

In [461]:
a1[5] = -5
a1

array([61, 24, 81, 70, 30, -5, 96, 84, 84, 97], dtype=int32)

In [462]:
a1[-1]

np.int32(97)

In [463]:
a1[-4] = -4
a1

array([61, 24, 81, 70, 30, -5, -4, 84, 84, 97], dtype=int32)

In [464]:
a2

array([[33, 12, 31],
       [62, 11, 97]], dtype=int32)

In [465]:
a2[1,2]

np.int32(97)

In [536]:
a2[1,2] = 3
a2

array([[ 33,  12, 999],
       [ 62,  99,   3]], dtype=int32)

In [467]:
a2[0,-1] = 999
a2

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

## 5.2 Slicing

In [468]:
a1

array([61, 24, 81, 70, 30, -5, -4, 84, 84, 97], dtype=int32)

In [469]:
a1[:5]

array([61, 24, 81, 70, 30], dtype=int32)

In [470]:
a1[5:]

array([-5, -4, 84, 84, 97], dtype=int32)

In [471]:
a1[2:8]

array([81, 70, 30, -5, -4, 84], dtype=int32)

In [472]:
a1[2:8:2]

array([81, 30, -4], dtype=int32)

In [473]:
a1[::3]

array([61, 70, -4, 97], dtype=int32)

In [474]:
a1[1::2]

array([24, 70, -5, 84, 97], dtype=int32)

In [475]:
a1[::-1]

array([97, 84, 84, -4, -5, 30, 70, 81, 24, 61], dtype=int32)

In [476]:
a1[::-2]

array([97, 84, -5, 70, 24], dtype=int32)

In [477]:
a2

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

In [478]:
a2[:1,]

array([[ 33,  12, 999]], dtype=int32)

In [479]:
a2[:2,]

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

In [480]:
a2[1:,]

array([[62, 11, 12]], dtype=int32)

In [481]:
a2[0:,]

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

In [ ]:
a2[1:,2:]
#dimensionen änder sich nicht durch slicing

array([[12]], dtype=int32)

In [483]:
a2[::-1,]

array([[ 62,  11,  12],
       [ 33,  12, 999]], dtype=int32)

In [484]:
a2[:,::-1]

array([[999,  12,  33],
       [ 12,  11,  62]], dtype=int32)

In [485]:
# Slicing von Spalten
a2

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

In [486]:
a2[:,0]

array([33, 62], dtype=int32)

In [487]:
a2[:,1]

array([12, 11], dtype=int32)

In [488]:
a2[:,2]

array([999,  12], dtype=int32)

In [489]:
# Slicing von Zeilen
a2

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

In [490]:
a2[0,:]

array([ 33,  12, 999], dtype=int32)

In [491]:
a2[1,:]

array([62, 11, 12], dtype=int32)

In [492]:
# kürzer:
a2[0]

array([ 33,  12, 999], dtype=int32)

In [493]:
a2[1]

array([62, 11, 12], dtype=int32)

In [494]:
a3

array([[[39, 47, 11, 73, 69],
        [30, 42, 85, 67, 31],
        [98, 58, 68, 51, 69],
        [89, 24, 71, 71, 56]],

       [[71, 60, 64, 73, 12],
        [60, 16, 30, 82, 48],
        [27, 13, 98, 69, 23],
        [18, 99, 62, 11, 93]],

       [[69, 80, 53, 17, 56],
        [44, 87, 90, 45, 59],
        [13, 11, 15, 63, 13],
        [63, 72, 27, 99, 53]]], dtype=int32)

In [495]:
a3[2]

array([[69, 80, 53, 17, 56],
       [44, 87, 90, 45, 59],
       [13, 11, 15, 63, 13],
       [63, 72, 27, 99, 53]], dtype=int32)

In [496]:
a4

array([[[[43, 83],
         [71, 23],
         [57, 24],
         [81, 87],
         [96, 71]],

        [[49, 94],
         [89, 91],
         [62, 33],
         [35, 98],
         [69, 50]]],


       [[[38, 24],
         [54, 74],
         [98, 80],
         [18, 97],
         [10, 17]],

        [[97, 72],
         [20, 90],
         [17, 44],
         [44, 42],
         [14, 50]]],


       [[[37, 16],
         [82, 81],
         [21, 43],
         [42, 57],
         [32, 71]],

        [[97, 46],
         [53, 95],
         [44, 74],
         [56, 87],
         [12, 10]]]], dtype=int32)

In [497]:
a4[1]

array([[[38, 24],
        [54, 74],
        [98, 80],
        [18, 97],
        [10, 17]],

       [[97, 72],
        [20, 90],
        [17, 44],
        [44, 42],
        [14, 50]]], dtype=int32)

In [498]:
a4[1:2,0:3,1:2]

array([[[[54, 74]],

        [[20, 90]]]], dtype=int32)

In [499]:
a2  # Slices erzeugen Views, keine Kopien!

array([[ 33,  12, 999],
       [ 62,  11,  12]], dtype=int32)

In [500]:
a_test = a2[:2,:2]
a_test

array([[33, 12],
       [62, 11]], dtype=int32)

In [501]:
a_test[1,1] = 99
a_test

array([[33, 12],
       [62, 99]], dtype=int32)

In [502]:
a2

array([[ 33,  12, 999],
       [ 62,  99,  12]], dtype=int32)

In [503]:
# copy erzeugt Kopie (später wird auch "deepcopy" benötigt)
a_test = a2[:2,:2].copy()
a_test

array([[33, 12],
       [62, 99]], dtype=int32)

In [504]:
a_test[1,1] = 77
a_test

array([[33, 12],
       [62, 77]], dtype=int32)

In [505]:
a2

array([[ 33,  12, 999],
       [ 62,  99,  12]], dtype=int32)

## 5.3 Shape und Reshape

In [506]:
m = np.array([2,3,5,7,11,13,17,19,23,29,31,37])

In [507]:
m.shape

(12,)

In [508]:
n = m.reshape((3,4))
n

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37]])

In [509]:
n.shape

(3, 4)

In [510]:
n.reshape(6,2)

array([[ 2,  3],
       [ 5,  7],
       [11, 13],
       [17, 19],
       [23, 29],
       [31, 37]])

In [511]:
n.reshape(2,6)

array([[ 2,  3,  5,  7, 11, 13],
       [17, 19, 23, 29, 31, 37]])

In [512]:
n.shape

(3, 4)

## 5.4 Verbinden von Arrays

In [513]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6,7])
m3 = np.array([8,9])

In [514]:
np.concatenate([m1,m2,m3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [515]:
n1 = np.mgrid[3:7, 8:11]
n1

array([[[ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6]],

       [[ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10]]])

In [516]:
n2 = np.mgrid[7:11, 11:14]
n2

array([[[ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]],

       [[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]]])

In [517]:
n3 = np.concatenate([n1, n2])
n3

array([[[ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6]],

       [[ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10]],

       [[ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]],

       [[11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]]])

In [518]:
n4 = np.concatenate([n1, n2], axis=1)
n4

array([[[ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]],

       [[ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [ 8,  9, 10],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13]]])

In [519]:
o1 = np.arange(1,4)
o2 = np.array([[4,5,6],[7,8,9],[10,11,12]])
o1, o2

(array([1, 2, 3]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

In [520]:
# o3 = np.concatenate([o1,o2])

In [521]:
# Vertikaler Stapel
o = np.vstack([o1,o2])
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [522]:
# Horizontaler Stapel
np.hstack([o1.reshape((3,1)),o2])

array([[ 1,  4,  5,  6],
       [ 2,  7,  8,  9],
       [ 3, 10, 11, 12]])

## 5.5 Zerlegen von Arrays

In [523]:
o

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [524]:
np.split(o, [1])

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])]

In [525]:
np.split(o, [1,2])

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [526]:
np.split(o, [1,3])

[array([[1, 2, 3]]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12]])]

In [527]:
np.split(o, [1,4])

[array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([], shape=(0, 3), dtype=int64)]

In [528]:
# vertikales Zerlegen
np.vsplit(o,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [529]:
# horizontales Zerlegen
np.hsplit(o,[2])

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

## 5.6 Vektorisierung (UFunctions)

In [537]:
# Beispiel zum Einstieg

def testrechnung(zahl):
    return np.sin(np.pi*zahl)

def testfunktion(zahlen):
    l = len(zahlen)
    result = np.empty(l)
    for i in range(l):
        result[i] = testrechnung(zahlen[i])
    return result

In [ ]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen)

array([ 8.32883620e-15,  1.22464680e-16,  3.67394040e-16,  5.87706667e-15,
       -2.54776053e-14, -1.46982375e-14, -2.94286620e-15, -4.91096681e-16,
       -6.85802208e-15,  4.88620758e-16])

In [ ]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion(zahlen)

14.1 ms ± 736 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [540]:
schneller = np.vectorize(testrechnung)
def testfunktion2(zahlen):
    return schneller(zahlen)

In [541]:
zahlen = np.random.randint(1,100, size=1000000)
%timeit testfunktion2(zahlen)

1.02 s ± 45.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [329]:
zahlen = np.random.randint(1,100, size=10)
testfunktion(zahlen), testfunktion2(zahlen)

(array([-4.89858720e-15, -1.46982375e-14, -3.13583858e-14, -1.56779550e-14,
        -9.79965032e-15,  1.66589104e-14,  1.95980627e-14,  1.56791929e-14,
         6.85926004e-15, -9.79965032e-15]),
 array([-4.89858720e-15, -1.46982375e-14, -3.13583858e-14, -1.56779550e-14,
        -9.79965032e-15,  1.66589104e-14,  1.95980627e-14,  1.56791929e-14,
         6.85926004e-15, -9.79965032e-15]))

In [330]:
# weitere eingebaute Vektorisierungen:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [331]:
print(a+1)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [332]:
print(a*2)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [333]:
a = np.mgrid[1:6,4:7]
a

array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]],

       [[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]]])

In [334]:
b = np.mgrid[0:5,2:5]
b

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]],

       [[2, 3, 4],
        [2, 3, 4],
        [2, 3, 4],
        [2, 3, 4],
        [2, 3, 4]]])

In [335]:
a*b

array([[[ 0,  0,  0],
        [ 2,  2,  2],
        [ 6,  6,  6],
        [12, 12, 12],
        [20, 20, 20]],

       [[ 8, 15, 24],
        [ 8, 15, 24],
        [ 8, 15, 24],
        [ 8, 15, 24],
        [ 8, 15, 24]]])

In [336]:
2**a

array([[[ 2,  2,  2],
        [ 4,  4,  4],
        [ 8,  8,  8],
        [16, 16, 16],
        [32, 32, 32]],

       [[16, 32, 64],
        [16, 32, 64],
        [16, 32, 64],
        [16, 32, 64],
        [16, 32, 64]]])

In [337]:
a*2-b

array([[[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]],

       [[6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8],
        [6, 7, 8]]])

In [338]:
np.exp(a)

array([[[  2.71828183,   2.71828183,   2.71828183],
        [  7.3890561 ,   7.3890561 ,   7.3890561 ],
        [ 20.08553692,  20.08553692,  20.08553692],
        [ 54.59815003,  54.59815003,  54.59815003],
        [148.4131591 , 148.4131591 , 148.4131591 ]],

       [[ 54.59815003, 148.4131591 , 403.42879349],
        [ 54.59815003, 148.4131591 , 403.42879349],
        [ 54.59815003, 148.4131591 , 403.42879349],
        [ 54.59815003, 148.4131591 , 403.42879349],
        [ 54.59815003, 148.4131591 , 403.42879349]]])

In [339]:
# wenn statt * multiply (analog +, - , //, % ...) verwendet wird, lässt sich die
# Ausgabe vorgeben:

in_data = np.arange(10)
in_data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [340]:
out_data = np.zeros(20)
out_data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [341]:
np.multiply(in_data, 2, out=out_data[5:15])

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [342]:
out_data

array([ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  4.,  6.,  8., 10., 12., 14.,
       16., 18.,  0.,  0.,  0.,  0.,  0.])

## 5.7 Reduktion und Akkumulation

In [343]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [344]:
np.multiply.reduce(a)

np.int64(24)

In [345]:
np.add.reduce(a)

np.int64(10)

In [346]:
a

array([1, 2, 3, 4])

In [347]:
np.add.accumulate(a)

array([ 1,  3,  6, 10])

In [348]:
np.multiply.accumulate(a)

array([ 1,  2,  6, 24])

## 5.8 Aggregation

In [349]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [350]:
sum(a)

np.int64(5050)

In [351]:
np.sum(a)

np.int64(5050)

In [352]:
testarray = np.random.rand(100000)

In [353]:
%timeit sum(testarray)

7.72 ms ± 383 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [354]:
%timeit np.sum(testarray)

47.8 μs ± 3.39 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [355]:
print(np.min(a), np.min(testarray))

1 3.5565008411619914e-06


In [356]:
print(np.max(a), np.max(testarray))

100 0.9999947904076273


In [357]:
# Mittelwert
print(np.mean(a), np.mean(testarray))

50.5 0.5006987039893867


In [358]:
# Standardabweichung
print(np.std(a), np.std(testarray))

28.86607004772212 0.2892456115713273


In [359]:
# Varianz
print(np.var(a), np.var(testarray))

833.25 0.08366302381327112


In [360]:
# Median
print(np.median(a), np.median(testarray))

50.5 0.5011878430651706


In [361]:
# Index des kleinsten Wertes
print(np.argmin(a), np.argmin(testarray))

0 57438


In [362]:
print(a[np.argmin(a)], testarray[np.argmin(testarray)])

1 3.5565008411619914e-06


In [363]:
# Index des größten Wertes
print(np.argmax(a), np.argmax(testarray))

99 84486


In [364]:
print(a[np.argmax(a)], testarray[np.argmax(testarray)])

100 0.9999947904076273


## 5.9 Test auf True

In [365]:
a1 = [False,False,False,False,False,False,False,False,False,False]
np.any(a1)

np.False_

In [366]:
a2 = [False,False,False,True,False,False,False,False,False,False]
np.any(a2)

np.True_

In [367]:
a3 = [True,False,True,True,True,True,True,True,True]
np.all(a3)

np.False_

In [368]:
a3 = [True,True,True,True,True,True,True,True,True]
np.all(a3)

np.True_

## 5.10 Broadcasting

In [369]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([2,3,4])

In [370]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [371]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [372]:
m2 - 1

array([1, 2, 3])

In [373]:
m1 + m2

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [374]:
m1 * m2

array([[ 2,  6, 12],
       [ 8, 15, 24]])

In [375]:
m1 * m2 * 2

array([[ 4, 12, 24],
       [16, 30, 48]])

In [376]:
m3 = np.random.random(10)
m3

array([0.75351989, 0.42117219, 0.51146192, 0.58826352, 0.99667717,
       0.95141589, 0.28533061, 0.73290144, 0.40718266, 0.6462338 ])

In [377]:
m3.mean()

np.float64(0.6294159087983929)

In [378]:
m3 = m3 - m3.mean()
m3

array([ 0.12410398, -0.20824372, -0.11795399, -0.04115239,  0.36726126,
        0.32199998, -0.3440853 ,  0.10348553, -0.22223325,  0.01681789])

In [379]:
m3.mean()

np.float64(-9.992007221626409e-17)

In [380]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [381]:
m1 < 3

array([[ True,  True, False],
       [False, False, False]])

In [382]:
m1 >= 4

array([[False, False, False],
       [ True,  True,  True]])

In [383]:
m1 < m2

array([[ True,  True,  True],
       [False, False, False]])

In [384]:
m2 <= m1

array([[False, False, False],
       [ True,  True,  True]])

In [385]:
np.count_nonzero([1,2,0,3,2])

4

In [386]:
np.count_nonzero(m1 < m2)

3

In [387]:
np.sum(m1 < 3)  # True 1 und False 0

np.int64(2)

In [388]:
np.any(m2 > 3)

np.True_

In [389]:
np.any(m2 > 4)

np.False_

In [390]:
np.all(m1 < 10)

np.True_

In [391]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [392]:
np.all(m1 < 4, axis = 0)

array([False, False, False])

In [393]:
np.all(m1 < 4, axis = 1)

array([ True, False])

In [394]:
m1 < 5

array([[ True,  True,  True],
       [ True, False, False]])

## 5.11 Maskierung

In [395]:
m1[m1 < 5]  

array([1, 2, 3, 4])

In [396]:
n1 = np.array([1,1,0,1,0,0,1,0], dtype = bool)
n2 = np.array([1,0,1,0,0,0,1,1], dtype = bool)

In [397]:
n1, n2

(array([ True,  True, False,  True, False, False,  True, False]),
 array([ True, False,  True, False, False, False,  True,  True]))

In [398]:
n1 & n2

array([ True, False, False, False, False, False,  True, False])

In [399]:
n1 | n2

array([ True,  True,  True,  True, False, False,  True,  True])

In [400]:
n1 ^ n2

array([False,  True,  True,  True, False, False, False,  True])

## 5.12 Fancy Indexing

In [401]:
beispiel = np.arange(20)+1
beispiel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [402]:
index_liste = [1,2,4,6,10,12,16,18]

In [403]:
beispiel[index_liste]

array([ 2,  3,  5,  7, 11, 13, 17, 19])

In [404]:
index_liste2 = np.array([[3,4,5],[7,8,9]])
index_liste2

array([[3, 4, 5],
       [7, 8, 9]])

In [405]:
beispiel[index_liste2]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [406]:
beispiel2 = np.mgrid[1:5,5:10]
beispiel2

array([[[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [407]:
index_liste3 = [3,2,1]

In [408]:
beispiel2[0,index_liste3]

array([[4, 4, 4, 4, 4],
       [3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2]])

In [409]:
beispiel2[1,index_liste3]

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [410]:
beispiel2[0,index_liste3[1:]]

array([[3, 3, 3, 3, 3],
       [2, 2, 2, 2, 2]])

In [411]:
beispiel2

array([[[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [412]:
beispiel2[0,index_liste3[1:]] = [[1,2,3,4,5],[6,7,8,9,10]]
beispiel2

array([[[ 1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

## 5.13 Sortieren

In [413]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [414]:
np.random.shuffle(a)
a

array([ 5, 11, 19,  4, 18,  9, 13,  1, 16, 17,  2, 10,  0, 12, 14,  8,  7,
        6,  3, 15])

In [415]:
np.sort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [416]:
beispiel2

array([[[ 1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [417]:
np.sort(beispiel2)

array([[[ 1,  1,  1,  1,  1],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [418]:
np.sort(beispiel2, axis = 0)

array([[[ 1,  1,  1,  1,  1],
        [ 5,  6,  7,  8,  9],
        [ 1,  2,  3,  4,  5],
        [ 4,  4,  4,  4,  4]],

       [[ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [419]:
np.sort(beispiel2, axis = 1)

array([[[ 1,  1,  1,  1,  1],
        [ 1,  2,  3,  4,  4],
        [ 4,  4,  4,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9]]])

In [420]:
np.sort(beispiel2, axis = None)

array([ 1,  1,  1,  1,  1,  1,  2,  3,  4,  4,  4,  4,  4,  4,  5,  5,  5,
        5,  5,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        9,  9,  9,  9,  9, 10])

In [421]:
a

array([ 5, 11, 19,  4, 18,  9, 13,  1, 16, 17,  2, 10,  0, 12, 14,  8,  7,
        6,  3, 15])

In [422]:
indices = np.argsort(a)
indices

array([12,  7, 10, 18,  3,  0, 17, 16, 15,  5, 11,  1, 13,  6, 14, 19,  8,
        9,  4,  2])

In [423]:
a[indices]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [424]:
a

array([ 5, 11, 19,  4, 18,  9, 13,  1, 16, 17,  2, 10,  0, 12, 14,  8,  7,
        6,  3, 15])

In [425]:
np.partition(a, 5) # Teilfunktion von Quicksort

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [426]:
np.argpartition(a,5)

array([12,  7, 10, 18,  3,  0, 17, 16, 15,  5, 11,  1, 13,  6, 14, 19,  8,
        9,  4,  2])

In [427]:
a[np.argpartition(a,5)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])