# Aufgabe 1

Beschreiben Sie anhand eigener Beispiele wie Sie Numpy-Arrays
umformen (reshape) und einzelne Bereiche in mehrdimensionalen
Arrays auswählen (Slices)!

In [13]:
import numpy as np
array = np.array([range(0,100)])
#print(array)
#print(array.shape)
array = array.reshape(10, 10)
#print(array)
#print(array.shape)

array = array.reshape(10, 5, 2)
#print(array)
#print(array.shape)

array = array.reshape(1, 5, 20)
#print(array)
#print(array.shape)

array = array.reshape(5, 5, 4)
print(array)
print(array[::2])
print(array.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]
(5, 5, 4)


# Aufgabe 2

Beschreiben Sie mit eigenen Worten (anhand des untenstehenden Code Beispiels), was man unter „Fancy-Indexing“ versteht!

Der Variable A wird einem NumpyArray zugewiesen mit 100 einträgen mit random Nummern von 0 bis 10 (aus dem Randomseed 42)
Aus diesem Array werden alle Int´s, die kleiner 6 sind ausgewählt und in eine weitere Liste geschrieben. Gleichzeitig wird diese Liste umgeformt in ein Array mit 17 Zeilenvektoren mit jemals 3 einträgen und der variablen b zugeordnet.

In [1]:
import numpy as np
np.random.seed(42)
a = np.random.randint(0,10,100) 
print(a)

b = a[a < 6].reshape(17,3)
print(b)

[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4 1 7 5 1 4 0 9 5 8 0 9 2 6 3 8 2 4 2 6 4 8
 6 1 3 8 1 9 8 9 4 1 3 6 7 2 0 3 1 7 3 1 5 5 9 3 5 1 9 1 9 3 7 6 8 7 4 1 4
 7 9 8 8 0 8 6 8 7 0 7 7 2 0 7 2 2 0 4 9 6 9 8 6 8 7]
[[3 4 2]
 [4 3 2]
 [5 4 1]
 [5 1 4]
 [0 5 0]
 [2 3 2]
 [4 2 4]
 [1 3 1]
 [4 1 3]
 [2 0 3]
 [1 3 1]
 [5 5 3]
 [5 1 1]
 [3 4 1]
 [4 0 0]
 [2 0 2]
 [2 0 4]]


# Aufgabe 3 

Bei der Vigenère-Verschlüsselung wird der Klartext mit einem festen
Schlüsselwort verrechnet. Dabei werden die Buchstaben anhand ihrer
Position im Alphabet addiert (A=1, B=2, …), wobei nach dem „Z=26“
wieder „A=1≙27“ folgt! Der Einfachheit halber werden Leerzeichen
nicht verschlüsselt. Das Passwort wird genau unter den Klartext immer
wiederholt, bis es genau die Länge des Klartextes hat.
Das Ergebnis ist der Chiffretext.

a) Programmieren Sie die Verschlüsselung von Klartext und
Passwort in Chiffretext!


In [3]:
text = 'DIES IST EIN KLARTEXT'
pw = 'SONNE'
pw1 = ''
i_1 = 0


text = text.upper()
pw = pw.upper()
result = ''
i= 0
for i in range(len(text)):
    if text[i] == ' ':
        result += ' '
    else:
        result += chr((ord(text[i]) + ord(pw[i_1 % len(pw)])+1) %26 + ord('A'))
        i_1 += 1

encrypted_text = result
print('Encrypted text:', encrypted_text)


Encrypted text: WXSG NLI SWS DAOFYXMH


b) Programmieren Sie die Entschlüsselung von Chiffretext und
Passwort in Klartext! 

In [8]:
text = 'WXSG NLI SWS DAOFYXMH'
pw = 'SONNE'
i_1 = 0


text = text.upper()
pw = pw.upper()
result = ''

for i in range(len(text)):
    if text[i] == ' ':
        result += ' '
    else:
        result += chr((ord(text[i]) - ord(pw[i_1 % len(pw)])-1) % 26 + ord('A'))
        i_1 += 1
    


decrypted_text = result
print('Decrypted text:', decrypted_text)

Decrypted text: DIES IST EIN KLARTEXT


c) Programmieren Sie im Rahmen der Kryptoanalyse einen „Known-Plaintext-Angriff“!
Hierbei wird aus dem Klartext und dem Chiffretext das
zugehörige Passwort ermittelt!


In [ ]:
text = 'DIES IST EIN KLARTEXT'
encrypted_text = 'WXSG NLI SWS DAOFYXMH'
pw = ''

for i in range(len(text)): 
    if text[i] == ' ':
        pw += ''
    else:
        pw += chr((ord(encrypted_text[i]) - ord(text[i]) - 1) % 26 + ord('A'))
PW = ''    
   
for i in range(len(pw)):
    PW += pw[i]
    if pw[i] == pw[i+1]:
        for j in range(i):
            if pw[i] == pw[j]:
                pw = pw[:j] + pw[j+1:]
                break

print(pw)

IndexError: string index out of range

d) Programmieren Sie im Rahmen der Kryptoanalyse einen
„Probable-Plaintext-Angriff“!
Dabei soll Ihr Programm einen Chiffretext ohne Passwort und
ohne Klartext ermitteln, indem systematisch immer längere
Passwörter geraten werden. Sie dürfen dabei einen Teil des
Klartextes vorgeben (ansonsten können Sie nicht überprüfen, ob
die Entschlüsselung erfolgreich ist) 

In [ ]:
# encrypted_text = 'WXSG NLI SWS DAOFYXMH'
# text = 'DIES IST '

# for i in range(len(text)):
#     if text[i] == ' ':
#         pw += ''
#     else:
#         pw += chr((ord(encrypted_text[i]) - ord(text[i])-1) % 26 + ord('A'))

# print(pw)


SONNESONNESOSONNESO
