# Aufgabe 1

Beschreiben Sie anhand eigener Beispiele wie Sie Numpy-Arrays
umformen (reshape) und einzelne Bereiche in mehrdimensionalen
Arrays auswählen (Slices)!

In [13]:
import numpy as np
array = np.array([range(0,100)])
#print(array)
#print(array.shape)
array = array.reshape(10, 10)
#print(array)
#print(array.shape)

array = array.reshape(10, 5, 2)
#print(array)
#print(array.shape)

array = array.reshape(1, 5, 20)
#print(array)
#print(array.shape)

array = array.reshape(5, 5, 4)
print(array)
print(array[::2])
print(array.shape)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]
(5, 5, 4)


# Aufgabe 2

Beschreiben Sie mit eigenen Worten (anhand des untenstehenden Code Beispiels), was man unter „Fancy-Indexing“ versteht!

Der Variable A wird einem NumpyArray zugewiesen mit 100 einträgen mit random Nummern von 0 bis 10 (aus dem Randomseed 42)
Aus diesem Array werden alle Int´s, die kleiner 6 sind ausgewählt und in eine weitere Liste geschrieben. Gleichzeitig wird diese Liste umgeformt in ein Array mit 17 Zeilenvektoren mit jemals 3 einträgen und der variablen b zugeordnet.

In [11]:
import numpy as np
np.random.seed(42)
a = np.random.randint(0,10,100) 
print(a)

b = a[a < 6].reshape(17,3)
print(b)

[6 3 7 4 6 9 2 6 7 4 3 7 7 2 5 4 1 7 5 1 4 0 9 5 8 0 9 2 6 3 8 2 4 2 6 4 8
 6 1 3 8 1 9 8 9 4 1 3 6 7 2 0 3 1 7 3 1 5 5 9 3 5 1 9 1 9 3 7 6 8 7 4 1 4
 7 9 8 8 0 8 6 8 7 0 7 7 2 0 7 2 2 0 4 9 6 9 8 6 8 7]
[[3 4 2]
 [4 3 2]
 [5 4 1]
 [5 1 4]
 [0 5 0]
 [2 3 2]
 [4 2 4]
 [1 3 1]
 [4 1 3]
 [2 0 3]
 [1 3 1]
 [5 5 3]
 [5 1 1]
 [3 4 1]
 [4 0 0]
 [2 0 2]
 [2 0 4]]


# Aufgabe 3 

Bei der Vigenère-Verschlüsselung wird der Klartext mit einem festen
Schlüsselwort verrechnet. Dabei werden die Buchstaben anhand ihrer
Position im Alphabet addiert (A=1, B=2, …), wobei nach dem „Z=26“
wieder „A=1≙27“ folgt! Der Einfachheit halber werden Leerzeichen
nicht verschlüsselt. Das Passwort wird genau unter den Klartext immer
wiederholt, bis es genau die Länge des Klartextes hat.
Das Ergebnis ist der Chiffretext.

a) Programmieren Sie die Verschlüsselung von Klartext und
Passwort in Chiffretext!


In [91]:
text = 'DIES IST EIN KLARTEXT'
pw = 'SONNE'
pw1 = ''
i_1 = 0

def encrypt(text, pw):
    global pw1, i_1
    text = text.upper()
    pw = pw.upper()
    result = ''
    i= 0
    for i in range(len(text)):
        if text[i] == ' ':
            result += ' '
            
        else:
            result += chr((ord(text[i]) + ord(pw[i_1 % len(pw)])+1) %26 + ord('A'))
            pw1 += pw[i_1 % len(pw)]
            i_1 += 1
            print(pw1)
            print(result)
            print((ord(text[i]) + ord(pw[i_1 % len(pw)]))%26+ord('A')+1)
    return result

encrypted_text = encrypt(text, pw)
print('Encrypted text:', encrypted_text)


S
W
83
SO
WX
87
SON
WXS
83
SONN
WXSG
88
SONNE
WXSG N
66
SONNES
WXSG NL
72
SONNESO
WXSG NLI
72
SONNESON
WXSG NLI S
83
SONNESONN
WXSG NLI SW
78
SONNESONNE
WXSG NLI SWS
71
SONNESONNES
WXSG NLI SWS D
90
SONNESONNESO
WXSG NLI SWS DA
90
SONNESONNESON
WXSG NLI SWS DAO
79
SONNESONNESONN
WXSG NLI SWS DAOF
87
SONNESONNESONNE
WXSG NLI SWS DAOFY
77
SONNESONNESONNES
WXSG NLI SWS DAOFYX
84
SONNESONNESONNESO
WXSG NLI SWS DAOFYXM
76
SONNESONNESONNESON
WXSG NLI SWS DAOFYXMH
72
Encrypted text: WXSG NLI SWS DAOFYXMH


In [82]:
chr(65)

'A'

b) Programmieren Sie die Entschlüsselung von Chiffretext und
Passwort in Klartext! 

In [92]:
encrypted_text = 'WXSG NLI SWS DAOFYXMH'
pw = 'SONNE'
i_1 = 0

def decrypt(text, pw):
    global i_1
    text = text.upper()
    pw = pw.upper()
    result = ''
    i= 0
    for i in range(len(text)):
        if text[i] == ' ':
            result += ' '
        else:
            result += chr((ord(text[i]) - ord(pw[i_1 % len(pw)])-1) % 26 + ord('A'))
            i_1 += 1
            print(result)
            print((ord(text[i]) + ord(pw[i % len(pw)])//90))
    return result

decrypted_text = decrypt(encrypted_text, pw)
print('Decrypted text:', decrypted_text)

D
87
DI
88
DIE
83
DIES
71
DIES I
78
DIES IS
76
DIES IST
73
DIES IST E
83
DIES IST EI
87
DIES IST EIN
83
DIES IST EIN K
68
DIES IST EIN KL
65
DIES IST EIN KLA
79
DIES IST EIN KLAR
70
DIES IST EIN KLART
89
DIES IST EIN KLARTE
88
DIES IST EIN KLARTEX
77
DIES IST EIN KLARTEXT
72
Decrypted text: DIES IST EIN KLARTEXT


c) Programmieren Sie im Rahmen der Kryptoanalyse einen „Known-Plaintext-Angriff“!
Hierbei wird aus dem Klartext und dem Chiffretext das
zugehörige Passwort ermittelt!


In [94]:
text = 'DIES IST EIN KLARTEXT'
encrypted_text = 'WXSG NLI SWS DAOFYXMH'
pw = ''

for i in range(len(text)): 
    if text[i] == ' ':
        pw += ''
    else:
        pw += chr((ord(encrypted_text[i]) - ord(text[i])-1) % 26 + ord('A'))
    
print(pw)

SONNESONNESONNESON


d) Programmieren Sie im Rahmen der Kryptoanalyse einen
„Probable-Plaintext-Angriff“!
Dabei soll Ihr Programm einen Chiffretext ohne Passwort und
ohne Klartext ermitteln, indem systematisch immer längere
Passwörter geraten werden. Sie dürfen dabei einen Teil des
Klartextes vorgeben (ansonsten können Sie nicht überprüfen, ob
die Entschlüsselung erfolgreich ist) 